/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ACLHistoryChange
 */
export interface ACLHistoryChange {
  /**
   *
   * @type {string}
   * @memberof ACLHistoryChange
   */
  action: string;
  /**
   *
   * @type {string}
   * @memberof ACLHistoryChange
   */
  target: string;
  /**
   *
   * @type {any}
   * @memberof ACLHistoryChange
   */
  readonly before: any | null;
  /**
   *
   * @type {any}
   * @memberof ACLHistoryChange
   */
  readonly after: any | null;
}

/**
 * Check if a given object implements the ACLHistoryChange interface.
 */
export function instanceOfACLHistoryChange(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "action" in value;
  isInstance = isInstance && "target" in value;
  isInstance = isInstance && "before" in value;
  isInstance = isInstance && "after" in value;

  return isInstance;
}

export function ACLHistoryChangeFromJSON(json: any): ACLHistoryChange {
  return ACLHistoryChangeFromJSONTyped(json, false);
}

export function ACLHistoryChangeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ACLHistoryChange {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    action: json["action"],
    target: json["target"],
    before: json["before"],
    after: json["after"],
  };
}

export function ACLHistoryChangeToJSON(value?: ACLHistoryChange | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    action: value.action,
    target: value.target,
  };
}
