/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ACLRoles
 */
export interface ACLRoles {
  /**
   *
   * @type {number}
   * @memberof ACLRoles
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof ACLRoles
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof ACLRoles
   */
  description?: string;
  /**
   *
   * @type {number}
   * @memberof ACLRoles
   */
  currentPermission?: number;
}

export function ACLRolesFromJSON(json: any): ACLRoles {
  return ACLRolesFromJSONTyped(json, false);
}

export function ACLRolesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ACLRoles {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    name: !exists(json, "name") ? undefined : json["name"],
    description: !exists(json, "description") ? undefined : json["description"],
    currentPermission: !exists(json, "current_permission")
      ? undefined
      : json["current_permission"],
  };
}

export function ACLRolesToJSON(value?: ACLRoles | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    description: value.description,
    current_permission: value.currentPermission,
  };
}
