/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  AdvancedSearchResultAttrInfo,
  AdvancedSearchResultAttrInfoFromJSON,
  AdvancedSearchResultAttrInfoFromJSONTyped,
  AdvancedSearchResultAttrInfoToJSON,
} from "./AdvancedSearchResultAttrInfo";

/**
 *
 * @export
 * @interface AdvancedSearch
 */
export interface AdvancedSearch {
  /**
   *
   * @type {Array<number>}
   * @memberof AdvancedSearch
   */
  entities: Array<number>;
  /**
   *
   * @type {string}
   * @memberof AdvancedSearch
   */
  entryName?: string;
  /**
   *
   * @type {Array<AdvancedSearchResultAttrInfo>}
   * @memberof AdvancedSearch
   */
  attrinfo: Array<AdvancedSearchResultAttrInfo>;
  /**
   *
   * @type {boolean}
   * @memberof AdvancedSearch
   */
  hasReferral?: boolean;
  /**
   *
   * @type {string}
   * @memberof AdvancedSearch
   */
  referralName?: string;
  /**
   *
   * @type {boolean}
   * @memberof AdvancedSearch
   */
  isOutputAll?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AdvancedSearch
   */
  isAllEntities?: boolean;
  /**
   *
   * @type {number}
   * @memberof AdvancedSearch
   */
  entryLimit?: number;
  /**
   *
   * @type {number}
   * @memberof AdvancedSearch
   */
  entryOffset?: number;
}

export function AdvancedSearchFromJSON(json: any): AdvancedSearch {
  return AdvancedSearchFromJSONTyped(json, false);
}

export function AdvancedSearchFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AdvancedSearch {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    entities: json["entities"],
    entryName: !exists(json, "entry_name") ? undefined : json["entry_name"],
    attrinfo: (json["attrinfo"] as Array<any>).map(
      AdvancedSearchResultAttrInfoFromJSON
    ),
    hasReferral: !exists(json, "has_referral")
      ? undefined
      : json["has_referral"],
    referralName: !exists(json, "referral_name")
      ? undefined
      : json["referral_name"],
    isOutputAll: !exists(json, "is_output_all")
      ? undefined
      : json["is_output_all"],
    isAllEntities: !exists(json, "is_all_entities")
      ? undefined
      : json["is_all_entities"],
    entryLimit: !exists(json, "entry_limit") ? undefined : json["entry_limit"],
    entryOffset: !exists(json, "entry_offset")
      ? undefined
      : json["entry_offset"],
  };
}

export function AdvancedSearchToJSON(value?: AdvancedSearch | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    entities: value.entities,
    entry_name: value.entryName,
    attrinfo: (value.attrinfo as Array<any>).map(
      AdvancedSearchResultAttrInfoToJSON
    ),
    has_referral: value.hasReferral,
    referral_name: value.referralName,
    is_output_all: value.isOutputAll,
    is_all_entities: value.isAllEntities,
    entry_limit: value.entryLimit,
    entry_offset: value.entryOffset,
  };
}
