/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AdvancedSearchResultAttrInfo
 */
export interface AdvancedSearchResultAttrInfo {
  /**
   *
   * @type {string}
   * @memberof AdvancedSearchResultAttrInfo
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof AdvancedSearchResultAttrInfo
   */
  filterKey?: AdvancedSearchResultAttrInfoFilterKeyEnum;
  /**
   *
   * @type {string}
   * @memberof AdvancedSearchResultAttrInfo
   */
  keyword?: string;
}

/**
 * @export
 */
export const AdvancedSearchResultAttrInfoFilterKeyEnum = {
  CLEARED: 0,
  EMPTY: 1,
  NON_EMPTY: 2,
  TEXT_CONTAINED: 3,
  TEXT_NOT_CONTAINED: 4,
  DUPLICATED: 5,
} as const;
export type AdvancedSearchResultAttrInfoFilterKeyEnum =
  typeof AdvancedSearchResultAttrInfoFilterKeyEnum[keyof typeof AdvancedSearchResultAttrInfoFilterKeyEnum];

/**
 * Check if a given object implements the AdvancedSearchResultAttrInfo interface.
 */
export function instanceOfAdvancedSearchResultAttrInfo(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "name" in value;

  return isInstance;
}

export function AdvancedSearchResultAttrInfoFromJSON(
  json: any
): AdvancedSearchResultAttrInfo {
  return AdvancedSearchResultAttrInfoFromJSONTyped(json, false);
}

export function AdvancedSearchResultAttrInfoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AdvancedSearchResultAttrInfo {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"],
    filterKey: !exists(json, "filter_key") ? undefined : json["filter_key"],
    keyword: !exists(json, "keyword") ? undefined : json["keyword"],
  };
}

export function AdvancedSearchResultAttrInfoToJSON(
  value?: AdvancedSearchResultAttrInfo | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    filter_key: value.filterKey,
    keyword: value.keyword,
  };
}
