/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  EntityAttr,
  EntityAttrFromJSON,
  EntityAttrFromJSONTyped,
  EntityAttrToJSON,
} from "./EntityAttr";
import {
  Webhook,
  WebhookFromJSON,
  WebhookFromJSONTyped,
  WebhookToJSON,
} from "./Webhook";

/**
 *
 * @export
 * @interface EntityCreate
 */
export interface EntityCreate {
  /**
   *
   * @type {number}
   * @memberof EntityCreate
   */
  readonly id: number;
  /**
   *
   * @type {string}
   * @memberof EntityCreate
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof EntityCreate
   */
  note?: string;
  /**
   *
   * @type {boolean}
   * @memberof EntityCreate
   */
  isToplevel?: boolean;
  /**
   *
   * @type {Array<EntityAttr>}
   * @memberof EntityCreate
   */
  attrs?: Array<EntityAttr>;
  /**
   *
   * @type {Array<Webhook>}
   * @memberof EntityCreate
   */
  webhooks?: Array<Webhook>;
}

export function EntityCreateFromJSON(json: any): EntityCreate {
  return EntityCreateFromJSONTyped(json, false);
}

export function EntityCreateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntityCreate {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    note: !exists(json, "note") ? undefined : json["note"],
    isToplevel: !exists(json, "is_toplevel") ? undefined : json["is_toplevel"],
    attrs: !exists(json, "attrs")
      ? undefined
      : (json["attrs"] as Array<any>).map(EntityAttrFromJSON),
    webhooks: !exists(json, "webhooks")
      ? undefined
      : (json["webhooks"] as Array<any>).map(WebhookFromJSON),
  };
}

export function EntityCreateToJSON(value?: EntityCreate | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    note: value.note,
    is_toplevel: value.isToplevel,
    attrs:
      value.attrs === undefined
        ? undefined
        : (value.attrs as Array<any>).map(EntityAttrToJSON),
    webhooks:
      value.webhooks === undefined
        ? undefined
        : (value.webhooks as Array<any>).map(WebhookToJSON),
  };
}
