/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EntityAttrName
 */
export interface EntityAttrName {
  /**
   *
   * @type {string}
   * @memberof EntityAttrName
   */
  name: string;
}

export function EntityAttrNameFromJSON(json: any): EntityAttrName {
  return EntityAttrNameFromJSONTyped(json, false);
}

export function EntityAttrNameFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntityAttrName {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"],
  };
}

export function EntityAttrNameToJSON(value?: EntityAttrName | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
  };
}
