/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Entity
 */
export interface Entity {
  /**
   *
   * @type {number}
   * @memberof Entity
   */
  readonly id: number;
  /**
   *
   * @type {string}
   * @memberof Entity
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Entity
   */
  note: string;
  /**
   *
   * @type {number}
   * @memberof Entity
   */
  status?: number;
  /**
   *
   * @type {boolean}
   * @memberof Entity
   */
  readonly isToplevel: boolean;
  /**
   *
   * @type {Array<{ [key: string]: any; }>}
   * @memberof Entity
   */
  readonly attrs: Array<{ [key: string]: any }>;
}

export function EntityFromJSON(json: any): Entity {
  return EntityFromJSONTyped(json, false);
}

export function EntityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Entity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    note: json["note"],
    status: !exists(json, "status") ? undefined : json["status"],
    isToplevel: json["is_toplevel"],
    attrs: json["attrs"],
  };
}

export function EntityToJSON(value?: Entity | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    note: value.note,
    status: value.status,
  };
}
