/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EntityAttributeType
 */
export interface EntityAttributeType {
  /**
   *
   * @type {number}
   * @memberof EntityAttributeType
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof EntityAttributeType
   */
  name: string;
}

export function EntityAttributeTypeFromJSON(json: any): EntityAttributeType {
  return EntityAttributeTypeFromJSONTyped(json, false);
}

export function EntityAttributeTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntityAttributeType {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
  };
}

export function EntityAttributeTypeToJSON(
  value?: EntityAttributeType | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
  };
}
