/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EntityImportExport
 */
export interface EntityImportExport {
  /**
   *
   * @type {number}
   * @memberof EntityImportExport
   */
  readonly id: number;
  /**
   *
   * @type {string}
   * @memberof EntityImportExport
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof EntityImportExport
   */
  note?: string;
  /**
   *
   * @type {number}
   * @memberof EntityImportExport
   */
  status?: number;
  /**
   *
   * @type {string}
   * @memberof EntityImportExport
   */
  createdUser: string;
}

export function EntityImportExportFromJSON(json: any): EntityImportExport {
  return EntityImportExportFromJSONTyped(json, false);
}

export function EntityImportExportFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntityImportExport {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    note: !exists(json, "note") ? undefined : json["note"],
    status: !exists(json, "status") ? undefined : json["status"],
    createdUser: json["created_user"],
  };
}

export function EntityImportExportToJSON(
  value?: EntityImportExport | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    note: value.note,
    status: value.status,
    created_user: value.createdUser,
  };
}
