/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EntityList
 */
export interface EntityList {
  /**
   *
   * @type {number}
   * @memberof EntityList
   */
  readonly id: number;
  /**
   *
   * @type {string}
   * @memberof EntityList
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof EntityList
   */
  note?: string;
  /**
   *
   * @type {number}
   * @memberof EntityList
   */
  status?: number;
  /**
   *
   * @type {boolean}
   * @memberof EntityList
   */
  readonly isToplevel: boolean;
}

export function EntityListFromJSON(json: any): EntityList {
  return EntityListFromJSONTyped(json, false);
}

export function EntityListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntityList {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    note: !exists(json, "note") ? undefined : json["note"],
    status: !exists(json, "status") ? undefined : json["status"],
    isToplevel: json["is_toplevel"],
  };
}

export function EntityListToJSON(value?: EntityList | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    note: value.note,
    status: value.status,
  };
}
