/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EntryExport
 */
export interface EntryExport {
  /**
   *
   * @type {string}
   * @memberof EntryExport
   */
  format: string;
}

export function EntryExportFromJSON(json: any): EntryExport {
  return EntryExportFromJSONTyped(json, false);
}

export function EntryExportFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntryExport {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    format: json["format"],
  };
}

export function EntryExportToJSON(value?: EntryExport | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    format: value.format,
  };
}
