/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  EntityAttributeType,
  EntityAttributeTypeFromJSON,
  EntityAttributeTypeFromJSONTyped,
  EntityAttributeTypeToJSON,
} from "./EntityAttributeType";
import {
  EntryAttributeValue,
  EntryAttributeValueFromJSON,
  EntryAttributeValueFromJSONTyped,
  EntryAttributeValueToJSON,
} from "./EntryAttributeValue";

/**
 *
 * @export
 * @interface EntryAttributeType
 */
export interface EntryAttributeType {
  /**
   *
   * @type {number}
   * @memberof EntryAttributeType
   */
  id: number | null;
  /**
   *
   * @type {number}
   * @memberof EntryAttributeType
   */
  type: number;
  /**
   *
   * @type {boolean}
   * @memberof EntryAttributeType
   */
  isMandatory: boolean;
  /**
   *
   * @type {EntryAttributeValue}
   * @memberof EntryAttributeType
   */
  value: EntryAttributeValue;
  /**
   *
   * @type {EntityAttributeType}
   * @memberof EntryAttributeType
   */
  schema: EntityAttributeType;
}

export function EntryAttributeTypeFromJSON(json: any): EntryAttributeType {
  return EntryAttributeTypeFromJSONTyped(json, false);
}

export function EntryAttributeTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntryAttributeType {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    type: json["type"],
    isMandatory: json["is_mandatory"],
    value: EntryAttributeValueFromJSON(json["value"]),
    schema: EntityAttributeTypeFromJSON(json["schema"]),
  };
}

export function EntryAttributeTypeToJSON(
  value?: EntryAttributeType | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    type: value.type,
    is_mandatory: value.isMandatory,
    value: EntryAttributeValueToJSON(value.value),
    schema: EntityAttributeTypeToJSON(value.schema),
  };
}
