/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EntryRetrieveSchema
 */
export interface EntryRetrieveSchema {
  /**
   *
   * @type {number}
   * @memberof EntryRetrieveSchema
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof EntryRetrieveSchema
   */
  name?: string;
}

export function EntryRetrieveSchemaFromJSON(json: any): EntryRetrieveSchema {
  return EntryRetrieveSchemaFromJSONTyped(json, false);
}

export function EntryRetrieveSchemaFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntryRetrieveSchema {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    name: !exists(json, "name") ? undefined : json["name"],
  };
}

export function EntryRetrieveSchemaToJSON(
  value?: EntryRetrieveSchema | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
  };
}
