/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EntryAttributeValueObject } from "./EntryAttributeValueObject";
import {
  EntryAttributeValueObjectFromJSON,
  EntryAttributeValueObjectFromJSONTyped,
  EntryAttributeValueObjectToJSON,
} from "./EntryAttributeValueObject";

/**
 *
 * @export
 * @interface EntryAttributeValueNamedObjectBoolean
 */
export interface EntryAttributeValueNamedObjectBoolean {
  /**
   *
   * @type {string}
   * @memberof EntryAttributeValueNamedObjectBoolean
   */
  name: string;
  /**
   *
   * @type {EntryAttributeValueObject}
   * @memberof EntryAttributeValueNamedObjectBoolean
   */
  object: EntryAttributeValueObject | null;
  /**
   *
   * @type {boolean}
   * @memberof EntryAttributeValueNamedObjectBoolean
   */
  _boolean: boolean;
}

/**
 * Check if a given object implements the EntryAttributeValueNamedObjectBoolean interface.
 */
export function instanceOfEntryAttributeValueNamedObjectBoolean(
  value: object
): boolean {
  let isInstance = true;
  isInstance = isInstance && "name" in value;
  isInstance = isInstance && "object" in value;
  isInstance = isInstance && "_boolean" in value;

  return isInstance;
}

export function EntryAttributeValueNamedObjectBooleanFromJSON(
  json: any
): EntryAttributeValueNamedObjectBoolean {
  return EntryAttributeValueNamedObjectBooleanFromJSONTyped(json, false);
}

export function EntryAttributeValueNamedObjectBooleanFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntryAttributeValueNamedObjectBoolean {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"],
    object: EntryAttributeValueObjectFromJSON(json["object"]),
    _boolean: json["boolean"],
  };
}

export function EntryAttributeValueNamedObjectBooleanToJSON(
  value?: EntryAttributeValueNamedObjectBoolean | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    object: EntryAttributeValueObjectToJSON(value.object),
    boolean: value._boolean,
  };
}
