/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  Entity,
  EntityFromJSON,
  EntityFromJSONTyped,
  EntityToJSON,
} from "./Entity";

/**
 *
 * @export
 * @interface EntryBase
 */
export interface EntryBase {
  /**
   *
   * @type {number}
   * @memberof EntryBase
   */
  readonly id: number;
  /**
   *
   * @type {string}
   * @memberof EntryBase
   */
  readonly name: string;
  /**
   *
   * @type {Entity}
   * @memberof EntryBase
   */
  readonly schema: Entity | null;
  /**
   *
   * @type {boolean}
   * @memberof EntryBase
   */
  readonly isActive: boolean;
}

export function EntryBaseFromJSON(json: any): EntryBase {
  return EntryBaseFromJSONTyped(json, false);
}

export function EntryBaseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntryBase {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    schema: EntityFromJSON(json["schema"]),
    isActive: json["is_active"],
  };
}

export function EntryBaseToJSON(value?: EntryBase | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {};
}
