/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  EntryImportAttribute,
  EntryImportAttributeFromJSON,
  EntryImportAttributeFromJSONTyped,
  EntryImportAttributeToJSON,
} from "./EntryImportAttribute";

/**
 *
 * @export
 * @interface EntryImportEntries
 */
export interface EntryImportEntries {
  /**
   *
   * @type {string}
   * @memberof EntryImportEntries
   */
  name: string;
  /**
   *
   * @type {Array<EntryImportAttribute>}
   * @memberof EntryImportEntries
   */
  attrs?: Array<EntryImportAttribute>;
}

export function EntryImportEntriesFromJSON(json: any): EntryImportEntries {
  return EntryImportEntriesFromJSONTyped(json, false);
}

export function EntryImportEntriesFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntryImportEntries {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"],
    attrs: !exists(json, "attrs")
      ? undefined
      : (json["attrs"] as Array<any>).map(EntryImportAttributeFromJSON),
  };
}

export function EntryImportEntriesToJSON(
  value?: EntryImportEntries | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    attrs:
      value.attrs === undefined
        ? undefined
        : (value.attrs as Array<any>).map(EntryImportAttributeToJSON),
  };
}
