/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { EntityAttributeType } from "./EntityAttributeType";
import {
  EntityAttributeTypeFromJSON,
  EntityAttributeTypeFromJSONTyped,
  EntityAttributeTypeToJSON,
} from "./EntityAttributeType";
import type { EntryAttributeValue } from "./EntryAttributeValue";
import {
  EntryAttributeValueFromJSON,
  EntryAttributeValueFromJSONTyped,
  EntryAttributeValueToJSON,
} from "./EntryAttributeValue";

/**
 *
 * @export
 * @interface EntryAttributeType
 */
export interface EntryAttributeType {
  /**
   *
   * @type {number}
   * @memberof EntryAttributeType
   */
  id: number | null;
  /**
   *
   * @type {number}
   * @memberof EntryAttributeType
   */
  type: EntryAttributeTypeTypeEnum;
  /**
   *
   * @type {boolean}
   * @memberof EntryAttributeType
   */
  isMandatory: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EntryAttributeType
   */
  isReadable: boolean;
  /**
   *
   * @type {EntryAttributeValue}
   * @memberof EntryAttributeType
   */
  value: EntryAttributeValue;
  /**
   *
   * @type {EntityAttributeType}
   * @memberof EntryAttributeType
   */
  schema: EntityAttributeType;
}

/**
 * @export
 */
export const EntryAttributeTypeTypeEnum = {
  OBJECT: 1,
  STRING: 2,
  NAMED_OBJECT: 2049,
  ARRAY_OBJECT: 1025,
  ARRAY_STRING: 1026,
  ARRAY_NAMED_OBJECT: 3073,
  ARRAY_NAMED_OBJECT_BOOLEAN: 3081,
  ARRAY_GROUP: 1040,
  ARRAY_ROLE: 1088,
  TEXT: 4,
  BOOLEAN: 8,
  GROUP: 16,
  DATE: 32,
  ROLE: 64,
} as const;
export type EntryAttributeTypeTypeEnum =
  typeof EntryAttributeTypeTypeEnum[keyof typeof EntryAttributeTypeTypeEnum];

/**
 * Check if a given object implements the EntryAttributeType interface.
 */
export function instanceOfEntryAttributeType(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "type" in value;
  isInstance = isInstance && "isMandatory" in value;
  isInstance = isInstance && "isReadable" in value;
  isInstance = isInstance && "value" in value;
  isInstance = isInstance && "schema" in value;

  return isInstance;
}

export function EntryAttributeTypeFromJSON(json: any): EntryAttributeType {
  return EntryAttributeTypeFromJSONTyped(json, false);
}

export function EntryAttributeTypeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntryAttributeType {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    type: json["type"],
    isMandatory: json["is_mandatory"],
    isReadable: json["is_readable"],
    value: EntryAttributeValueFromJSON(json["value"]),
    schema: EntityAttributeTypeFromJSON(json["schema"]),
  };
}

export function EntryAttributeTypeToJSON(
  value?: EntryAttributeType | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    type: value.type,
    is_mandatory: value.isMandatory,
    is_readable: value.isReadable,
    value: EntryAttributeValueToJSON(value.value),
    schema: EntityAttributeTypeToJSON(value.schema),
  };
}
