/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  Attribute,
  AttributeFromJSON,
  AttributeFromJSONTyped,
  AttributeToJSON,
} from "./Attribute";
import {
  EntryAttributeValue,
  EntryAttributeValueFromJSON,
  EntryAttributeValueFromJSONTyped,
  EntryAttributeValueToJSON,
} from "./EntryAttributeValue";

/**
 *
 * @export
 * @interface EntryHistoryAttributeValue
 */
export interface EntryHistoryAttributeValue {
  /**
   *
   * @type {number}
   * @memberof EntryHistoryAttributeValue
   */
  readonly id: number;
  /**
   *
   * @type {number}
   * @memberof EntryHistoryAttributeValue
   */
  type: number;
  /**
   *
   * @type {Date}
   * @memberof EntryHistoryAttributeValue
   */
  readonly createdTime: Date;
  /**
   *
   * @type {boolean}
   * @memberof EntryHistoryAttributeValue
   */
  isLatest?: boolean;
  /**
   *
   * @type {string}
   * @memberof EntryHistoryAttributeValue
   */
  createdUser: string;
  /**
   *
   * @type {EntryAttributeValue}
   * @memberof EntryHistoryAttributeValue
   */
  readonly currValue: EntryAttributeValue | null;
  /**
   *
   * @type {EntryAttributeValue}
   * @memberof EntryHistoryAttributeValue
   */
  readonly prevValue: EntryAttributeValue | null;
  /**
   *
   * @type {Attribute}
   * @memberof EntryHistoryAttributeValue
   */
  parentAttr: Attribute;
}

export function EntryHistoryAttributeValueFromJSON(
  json: any
): EntryHistoryAttributeValue {
  return EntryHistoryAttributeValueFromJSONTyped(json, false);
}

export function EntryHistoryAttributeValueFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): EntryHistoryAttributeValue {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    type: json["type"],
    createdTime: new Date(json["created_time"]),
    isLatest: !exists(json, "is_latest") ? undefined : json["is_latest"],
    createdUser: json["created_user"],
    currValue: EntryAttributeValueFromJSON(json["curr_value"]),
    prevValue: EntryAttributeValueFromJSON(json["prev_value"]),
    parentAttr: AttributeFromJSON(json["parent_attr"]),
  };
}

export function EntryHistoryAttributeValueToJSON(
  value?: EntryHistoryAttributeValue | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: value.type,
    is_latest: value.isLatest,
    created_user: value.createdUser,
    parent_attr: AttributeToJSON(value.parentAttr),
  };
}
