/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetEntryWithAttrAttrs
 */
export interface GetEntryWithAttrAttrs {
  /**
   *
   * @type {number}
   * @memberof GetEntryWithAttrAttrs
   */
  id?: number | null;
  /**
   *
   * @type {number}
   * @memberof GetEntryWithAttrAttrs
   */
  type?: number;
  /**
   *
   * @type {any}
   * @memberof GetEntryWithAttrAttrs
   */
  value?: any | null;
  /**
   *
   * @type {number}
   * @memberof GetEntryWithAttrAttrs
   */
  schemaId?: number;
  /**
   *
   * @type {string}
   * @memberof GetEntryWithAttrAttrs
   */
  schemaName?: string;
}

export function GetEntryWithAttrAttrsFromJSON(
  json: any
): GetEntryWithAttrAttrs {
  return GetEntryWithAttrAttrsFromJSONTyped(json, false);
}

export function GetEntryWithAttrAttrsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetEntryWithAttrAttrs {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    type: !exists(json, "type") ? undefined : json["type"],
    value: !exists(json, "value") ? undefined : json["value"],
    schemaId: !exists(json, "schema_id") ? undefined : json["schema_id"],
    schemaName: !exists(json, "schema_name") ? undefined : json["schema_name"],
  };
}

export function GetEntryWithAttrAttrsToJSON(
  value?: GetEntryWithAttrAttrs | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    type: value.type,
    value: value.value,
    schema_id: value.schemaId,
    schema_name: value.schemaName,
  };
}
