/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GetEntrySimple
 */
export interface GetEntrySimple {
  /**
   *
   * @type {number}
   * @memberof GetEntrySimple
   */
  readonly id: number;
  /**
   *
   * @type {string}
   * @memberof GetEntrySimple
   */
  name: string;
}

export function GetEntrySimpleFromJSON(json: any): GetEntrySimple {
  return GetEntrySimpleFromJSONTyped(json, false);
}

export function GetEntrySimpleFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GetEntrySimple {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
  };
}

export function GetEntrySimpleToJSON(value?: GetEntrySimple | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
  };
}
