/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface GroupCreateUpdate
 */
export interface GroupCreateUpdate {
  /**
   *
   * @type {number}
   * @memberof GroupCreateUpdate
   */
  readonly id: number;
  /**
   *
   * @type {string}
   * @memberof GroupCreateUpdate
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof GroupCreateUpdate
   */
  parentGroup?: number | null;
  /**
   *
   * @type {Array<number>}
   * @memberof GroupCreateUpdate
   */
  members?: Array<number>;
}

/**
 * Check if a given object implements the GroupCreateUpdate interface.
 */
export function instanceOfGroupCreateUpdate(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "name" in value;

  return isInstance;
}

export function GroupCreateUpdateFromJSON(json: any): GroupCreateUpdate {
  return GroupCreateUpdateFromJSONTyped(json, false);
}

export function GroupCreateUpdateFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): GroupCreateUpdate {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    parentGroup: !exists(json, "parent_group")
      ? undefined
      : json["parent_group"],
    members: !exists(json, "members") ? undefined : json["members"],
  };
}

export function GroupCreateUpdateToJSON(value?: GroupCreateUpdate | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    parent_group: value.parentGroup,
    members: value.members,
  };
}
