/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { GroupMember } from "./GroupMember";
import {
  GroupMemberFromJSON,
  GroupMemberFromJSONTyped,
  GroupMemberToJSON,
} from "./GroupMember";

/**
 *
 * @export
 * @interface Group
 */
export interface Group {
  /**
   *
   * @type {number}
   * @memberof Group
   */
  readonly id: number;
  /**
   *
   * @type {string}
   * @memberof Group
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof Group
   */
  parentGroup?: number | null;
  /**
   *
   * @type {Array<GroupMember>}
   * @memberof Group
   */
  readonly members: Array<GroupMember>;
}

/**
 * Check if a given object implements the Group interface.
 */
export function instanceOfGroup(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "name" in value;
  isInstance = isInstance && "members" in value;

  return isInstance;
}

export function GroupFromJSON(json: any): Group {
  return GroupFromJSONTyped(json, false);
}

export function GroupFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Group {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    name: json["name"],
    parentGroup: !exists(json, "parent_group")
      ? undefined
      : json["parent_group"],
    members: (json["members"] as Array<any>).map(GroupMemberFromJSON),
  };
}

export function GroupToJSON(value?: Group | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    parent_group: value.parentGroup,
  };
}
