/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface JobSerializersTarget
 */
export interface JobSerializersTarget {
  /**
   *
   * @type {number}
   * @memberof JobSerializersTarget
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof JobSerializersTarget
   */
  name?: string;
}

export function JobSerializersTargetFromJSON(json: any): JobSerializersTarget {
  return JobSerializersTargetFromJSONTyped(json, false);
}

export function JobSerializersTargetFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): JobSerializersTarget {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    name: !exists(json, "name") ? undefined : json["name"],
  };
}

export function JobSerializersTargetToJSON(
  value?: JobSerializersTarget | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
  };
}
