/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  EntityHistory,
  EntityHistoryFromJSON,
  EntityHistoryFromJSONTyped,
  EntityHistoryToJSON,
} from "./EntityHistory";

/**
 *
 * @export
 * @interface PaginatedEntityHistoryList
 */
export interface PaginatedEntityHistoryList {
  /**
   *
   * @type {number}
   * @memberof PaginatedEntityHistoryList
   */
  count?: number;
  /**
   *
   * @type {string}
   * @memberof PaginatedEntityHistoryList
   */
  next?: string | null;
  /**
   *
   * @type {string}
   * @memberof PaginatedEntityHistoryList
   */
  previous?: string | null;
  /**
   *
   * @type {Array<EntityHistory>}
   * @memberof PaginatedEntityHistoryList
   */
  results?: Array<EntityHistory>;
}

export function PaginatedEntityHistoryListFromJSON(
  json: any
): PaginatedEntityHistoryList {
  return PaginatedEntityHistoryListFromJSONTyped(json, false);
}

export function PaginatedEntityHistoryListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PaginatedEntityHistoryList {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    count: !exists(json, "count") ? undefined : json["count"],
    next: !exists(json, "next") ? undefined : json["next"],
    previous: !exists(json, "previous") ? undefined : json["previous"],
    results: !exists(json, "results")
      ? undefined
      : (json["results"] as Array<any>).map(EntityHistoryFromJSON),
  };
}

export function PaginatedEntityHistoryListToJSON(
  value?: PaginatedEntityHistoryList | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    count: value.count,
    next: value.next,
    previous: value.previous,
    results:
      value.results === undefined
        ? undefined
        : (value.results as Array<any>).map(EntityHistoryToJSON),
  };
}
