/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  EntryHistoryAttributeValue,
  EntryHistoryAttributeValueFromJSON,
  EntryHistoryAttributeValueFromJSONTyped,
  EntryHistoryAttributeValueToJSON,
} from "./EntryHistoryAttributeValue";

/**
 *
 * @export
 * @interface PaginatedEntryHistoryAttributeValueList
 */
export interface PaginatedEntryHistoryAttributeValueList {
  /**
   *
   * @type {number}
   * @memberof PaginatedEntryHistoryAttributeValueList
   */
  count?: number;
  /**
   *
   * @type {string}
   * @memberof PaginatedEntryHistoryAttributeValueList
   */
  next?: string | null;
  /**
   *
   * @type {string}
   * @memberof PaginatedEntryHistoryAttributeValueList
   */
  previous?: string | null;
  /**
   *
   * @type {Array<EntryHistoryAttributeValue>}
   * @memberof PaginatedEntryHistoryAttributeValueList
   */
  results?: Array<EntryHistoryAttributeValue>;
}

export function PaginatedEntryHistoryAttributeValueListFromJSON(
  json: any
): PaginatedEntryHistoryAttributeValueList {
  return PaginatedEntryHistoryAttributeValueListFromJSONTyped(json, false);
}

export function PaginatedEntryHistoryAttributeValueListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PaginatedEntryHistoryAttributeValueList {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    count: !exists(json, "count") ? undefined : json["count"],
    next: !exists(json, "next") ? undefined : json["next"],
    previous: !exists(json, "previous") ? undefined : json["previous"],
    results: !exists(json, "results")
      ? undefined
      : (json["results"] as Array<any>).map(EntryHistoryAttributeValueFromJSON),
  };
}

export function PaginatedEntryHistoryAttributeValueListToJSON(
  value?: PaginatedEntryHistoryAttributeValueList | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    count: value.count,
    next: value.next,
    previous: value.previous,
    results:
      value.results === undefined
        ? undefined
        : (value.results as Array<any>).map(EntryHistoryAttributeValueToJSON),
  };
}
