/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UserPasswordBySuperuser
 */
export interface UserPasswordBySuperuser {
  /**
   *
   * @type {string}
   * @memberof UserPasswordBySuperuser
   */
  newPasswd: string;
  /**
   *
   * @type {string}
   * @memberof UserPasswordBySuperuser
   */
  chkPasswd: string;
}

export function UserPasswordBySuperuserFromJSON(
  json: any
): UserPasswordBySuperuser {
  return UserPasswordBySuperuserFromJSONTyped(json, false);
}

export function UserPasswordBySuperuserFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserPasswordBySuperuser {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    newPasswd: json["new_passwd"],
    chkPasswd: json["chk_passwd"],
  };
}

export function UserPasswordBySuperuserToJSON(
  value?: UserPasswordBySuperuser | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    new_passwd: value.newPasswd,
    chk_passwd: value.chkPasswd,
  };
}
