/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UserPassword
 */
export interface UserPassword {
  /**
   *
   * @type {string}
   * @memberof UserPassword
   */
  oldPasswd: string;
  /**
   *
   * @type {string}
   * @memberof UserPassword
   */
  newPasswd: string;
  /**
   *
   * @type {string}
   * @memberof UserPassword
   */
  chkPasswd: string;
}

export function UserPasswordFromJSON(json: any): UserPassword {
  return UserPasswordFromJSONTyped(json, false);
}

export function UserPasswordFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserPassword {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    oldPasswd: json["old_passwd"],
    newPasswd: json["new_passwd"],
    chkPasswd: json["chk_passwd"],
  };
}

export function UserPasswordToJSON(value?: UserPassword | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    old_passwd: value.oldPasswd,
    new_passwd: value.newPasswd,
    chk_passwd: value.chkPasswd,
  };
}
