/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { UserRetrieveToken } from "./UserRetrieveToken";
import {
  UserRetrieveTokenFromJSON,
  UserRetrieveTokenFromJSONTyped,
  UserRetrieveTokenToJSON,
} from "./UserRetrieveToken";

/**
 *
 * @export
 * @interface UserRetrieve
 */
export interface UserRetrieve {
  /**
   *
   * @type {number}
   * @memberof UserRetrieve
   */
  readonly id: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   * @type {string}
   * @memberof UserRetrieve
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof UserRetrieve
   */
  email?: string;
  /**
   * Designates that this user has all permissions without explicitly assigning them.
   * @type {boolean}
   * @memberof UserRetrieve
   */
  isSuperuser?: boolean;
  /**
   *
   * @type {string}
   * @memberof UserRetrieve
   */
  readonly dateJoined: string;
  /**
   *
   * @type {UserRetrieveToken}
   * @memberof UserRetrieve
   */
  readonly token: UserRetrieveToken;
  /**
   *
   * @type {number}
   * @memberof UserRetrieve
   */
  authenticateType: UserRetrieveAuthenticateTypeEnum;
}

/**
 * @export
 */
export const UserRetrieveAuthenticateTypeEnum = {
  AUTH_TYPE_LOCAL: 1,
  AUTH_TYPE_LDAP: 2,
} as const;
export type UserRetrieveAuthenticateTypeEnum =
  typeof UserRetrieveAuthenticateTypeEnum[keyof typeof UserRetrieveAuthenticateTypeEnum];

/**
 * Check if a given object implements the UserRetrieve interface.
 */
export function instanceOfUserRetrieve(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "username" in value;
  isInstance = isInstance && "dateJoined" in value;
  isInstance = isInstance && "token" in value;
  isInstance = isInstance && "authenticateType" in value;

  return isInstance;
}

export function UserRetrieveFromJSON(json: any): UserRetrieve {
  return UserRetrieveFromJSONTyped(json, false);
}

export function UserRetrieveFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UserRetrieve {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    username: json["username"],
    email: !exists(json, "email") ? undefined : json["email"],
    isSuperuser: !exists(json, "is_superuser")
      ? undefined
      : json["is_superuser"],
    dateJoined: json["date_joined"],
    token: UserRetrieveTokenFromJSON(json["token"]),
    authenticateType: json["authenticate_type"],
  };
}

export function UserRetrieveToJSON(value?: UserRetrieve | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    username: value.username,
    email: value.email,
    is_superuser: value.isSuperuser,
    authenticate_type: value.authenticateType,
  };
}
