/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface WebhookHeaders
 */
export interface WebhookHeaders {
  /**
   *
   * @type {string}
   * @memberof WebhookHeaders
   */
  headerKey: string;
  /**
   *
   * @type {string}
   * @memberof WebhookHeaders
   */
  headerValue: string;
}

export function WebhookHeadersFromJSON(json: any): WebhookHeaders {
  return WebhookHeadersFromJSONTyped(json, false);
}

export function WebhookHeadersFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): WebhookHeaders {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    headerKey: json["header_key"],
    headerValue: json["header_value"],
  };
}

export function WebhookHeadersToJSON(value?: WebhookHeaders | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    header_key: value.headerKey,
    header_value: value.headerValue,
  };
}
