/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface WebhookPost
 */
export interface WebhookPost {
  /**
   *
   * @type {number}
   * @memberof WebhookPost
   */
  readonly id: number;
  /**
   *
   * @type {string}
   * @memberof WebhookPost
   */
  label: string;
  /**
   *
   * @type {string}
   * @memberof WebhookPost
   */
  url: string;
  /**
   *
   * @type {boolean}
   * @memberof WebhookPost
   */
  isEnabled?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof WebhookPost
   */
  isVerified?: boolean;
  /**
   *
   * @type {Array<{ [key: string]: string; }>}
   * @memberof WebhookPost
   */
  headers: Array<{ [key: string]: string }>;
}

export function WebhookPostFromJSON(json: any): WebhookPost {
  return WebhookPostFromJSONTyped(json, false);
}

export function WebhookPostFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): WebhookPost {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    label: json["label"],
    url: json["url"],
    isEnabled: !exists(json, "is_enabled") ? undefined : json["is_enabled"],
    isVerified: !exists(json, "is_verified") ? undefined : json["is_verified"],
    headers: json["headers"],
  };
}

export function WebhookPostToJSON(value?: WebhookPost | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    label: value.label,
    url: value.url,
    is_enabled: value.isEnabled,
    is_verified: value.isVerified,
    headers: value.headers,
  };
}
