import {
  Table,
  TableContainer,
  TableHead,
  TableBody,
  TableCell,
  TableRow,
  Paper,
} from "@mui/material";
import { styled } from "@mui/material/styles";
import React, { FC } from "react";

import { EntryAttributeType } from "../../apiclient/autogenerated";

import { AttributeValue } from "components/entry/AttributeValue";

interface Props {
  attributes: Array<EntryAttributeType>;
}

const StyledTableRow = styled(TableRow)(() => ({
  "&:nth-of-type(odd)": {
    backgroundColor: "#607D8B0A",
  },
  "&:last-child td, &:last-child th": {
    border: 0,
  },
}));

export const EntryAttributes: FC<Props> = ({ attributes }) => {
  return (
    <TableContainer component={Paper}>
      <Table>
        <TableHead sx={{ backgroundColor: "primary.dark" }}>
          <TableRow>
            <TableCell sx={{ color: "primary.contrastText" }}>項目</TableCell>
            <TableCell sx={{ color: "primary.contrastText" }}>内容</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {attributes.map((attr) => (
            <StyledTableRow key={attr.schema.name}>
              <TableCell sx={{ width: "200px", wordBreak: "break-word" }}>
                {attr.schema.name}
              </TableCell>
              <TableCell
                sx={{ width: "950px", p: "0px", wordBreak: "break-word" }}
              >
                <AttributeValue
                  attrInfo={{ type: attr.type, value: attr.value }}
                />
              </TableCell>
            </StyledTableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
  );
};
