/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import {
  PaginatedJobList,
  PaginatedJobListFromJSON,
  PaginatedJobListToJSON,
} from "../models";

export interface JobApiV2JobsListRequest {
  limit?: number;
  offset?: number;
}

/**
 *
 */
export class JobApi extends runtime.BaseAPI {
  /**
   */
  async jobApiV2JobsListRaw(
    requestParameters: JobApiV2JobsListRequest,
    initOverrides?: RequestInit
  ): Promise<runtime.ApiResponse<PaginatedJobList>> {
    const queryParameters: any = {};

    if (requestParameters.limit !== undefined) {
      queryParameters["limit"] = requestParameters.limit;
    }

    if (requestParameters.offset !== undefined) {
      queryParameters["offset"] = requestParameters.offset;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (
      this.configuration &&
      (this.configuration.username !== undefined ||
        this.configuration.password !== undefined)
    ) {
      headerParameters["Authorization"] =
        "Basic " +
        btoa(this.configuration.username + ":" + this.configuration.password);
    }
    if (this.configuration && this.configuration.apiKey) {
      headerParameters["Authorization"] =
        this.configuration.apiKey("Authorization"); // tokenAuth authentication
    }

    const response = await this.request(
      {
        path: `/job/api/v2/jobs`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PaginatedJobListFromJSON(jsonValue)
    );
  }

  /**
   */
  async jobApiV2JobsList(
    requestParameters: JobApiV2JobsListRequest = {},
    initOverrides?: RequestInit
  ): Promise<PaginatedJobList> {
    const response = await this.jobApiV2JobsListRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
