import {
  Box,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
  Typography,
} from "@mui/material";
import { styled } from "@mui/material/styles";
import React, { Fragment, FC, useState } from "react";

import { AttributeRow } from "./AttributeRow";

import { Entity, EntityUpdate } from "apiclient/autogenerated";

const HeaderTableRow = styled(TableRow)(({}) => ({
  backgroundColor: "#455A64",
}));

const HeaderTableCell = styled(TableCell)(({}) => ({
  color: "#FFFFFF",
}));

interface Props {
  entityInfo: EntityUpdate;
  setEntityInfo: (entityInfo: EntityUpdate) => void;
  referralEntities: Entity[];
}

export const AttributesFields: FC<Props> = ({
  entityInfo,
  setEntityInfo,
  referralEntities,
}) => {
  const [latestChangedIndex, setLatestChangedIndex] = useState<number | null>(
    null
  );

  return (
    <Box mb="80px">
      <Box my="16px">
        <Typography variant="h4" align="center">
          属性情報
        </Typography>
      </Box>

      <Table>
        <TableHead>
          <HeaderTableRow>
            <HeaderTableCell>属性名</HeaderTableCell>
            <HeaderTableCell>型</HeaderTableCell>
            <HeaderTableCell>必須</HeaderTableCell>
            <HeaderTableCell>関連削除</HeaderTableCell>
            <HeaderTableCell>並び替え</HeaderTableCell>
            <HeaderTableCell>削除</HeaderTableCell>
            <HeaderTableCell>追加</HeaderTableCell>
            <HeaderTableCell>ACL設定</HeaderTableCell>
          </HeaderTableRow>
        </TableHead>
        <TableBody>
          <>
            {entityInfo.attrs?.map((attr, index) => (
              <Fragment key={index}>
                {attr.isDeleted !== true && (
                  <AttributeRow
                    index={index}
                    currentAttr={attr}
                    allAttrs={entityInfo.attrs ?? []}
                    referralEntities={referralEntities}
                    entityInfo={entityInfo}
                    setEntityInfo={setEntityInfo}
                    latestChangedIndex={latestChangedIndex}
                    setLatestChangedIndex={setLatestChangedIndex}
                  />
                )}
              </Fragment>
            ))}
            {entityInfo.attrs?.filter((attr) => !attr.isDeleted).length ===
              0 && (
              <AttributeRow
                allAttrs={entityInfo.attrs}
                referralEntities={referralEntities}
                entityInfo={entityInfo}
                setEntityInfo={setEntityInfo}
                latestChangedIndex={latestChangedIndex}
                setLatestChangedIndex={setLatestChangedIndex}
              />
            )}
          </>
        </TableBody>
      </Table>
    </Box>
  );
};
