import {
  EntryRetrieveAttrs,
  EntryRetrieveValueAsObject,
  EntryRetrieveValueAsObjectSchema,
} from "../../../apiclient/autogenerated";

type EditableEntryAttrValue = {
  asObject?: EntryRetrieveValueAsObject;
  asString?: string;
  asNamedObject?: { [key: string]: EntryRetrieveValueAsObject };
  asArrayObject?: Array<EntryRetrieveValueAsObject>;
  asArrayString?: Array<string>;
  asArrayNamedObject?: Array<{ [key: string]: EntryRetrieveValueAsObject }>;
  asArrayGroup?: Array<EntryRetrieveValueAsObjectSchema>;
  asBoolean?: boolean;
  asGroup?: EntryRetrieveValueAsObjectSchema;
};

export type EditableEntry = {
  name: string;
  attrs: Record<string, EditableEntryAttrs>;
};

export type EditableEntryAttrs = Pick<
  EntryRetrieveAttrs,
  "id" | "type" | "isMandatory" | "schema"
> & {
  value: EditableEntryAttrValue;
};
