import {
  EntryAttributeType,
  EntryAttributeValueGroup,
  EntryAttributeValueObject,
  EntryAttributeValueRole,
} from "../../../apiclient/autogenerated";

export type EditableEntryAttrValue = {
  asObject?: EntryAttributeValueObject;
  asString?: string;
  asNamedObject?: Record<string, EntryAttributeValueObject>;
  asArrayObject?: Array<EntryAttributeValueObject>;
  asArrayString?: Array<string>;
  asArrayNamedObject?: Array<Record<string, EntryAttributeValueObject>>;
  asArrayGroup?: Array<EntryAttributeValueGroup>;
  asArrayRole?: Array<EntryAttributeValueRole>;
  asBoolean?: boolean;
  asGroup?: EntryAttributeValueGroup;
  asRole?: EntryAttributeValueRole;
};

export type EditableEntry = {
  name: string;
  attrs: Record<string, EditableEntryAttrs>;
};

export type EditableEntryAttrs = Pick<
  EntryAttributeType,
  "id" | "type" | "isMandatory" | "schema"
> & {
  value: EditableEntryAttrValue;
};
