import {
  AutocompleteChangeReason,
  AutocompleteInputChangeReason,
} from "@mui/base/AutocompleteUnstyled/useAutocomplete";
import { Autocomplete, TextField } from "@mui/material";
import React, { FC, useState } from "react";
import { useAsync } from "react-use";

import { aironeApiClientV2 } from "../../../apiclient/AironeApiClientV2";
import { GetEntryAttrReferral } from "../../../apiclient/autogenerated";

interface Props {
  schemaId: number;
  value: GetEntryAttrReferral | GetEntryAttrReferral[] | null;
  handleChange: (
    value: GetEntryAttrReferral | GetEntryAttrReferral[] | null
  ) => void;
  multiple?: boolean;
  disabled?: boolean;
  error?: { message?: string };
}

export const ReferralsAutocomplete: FC<Props> = ({
  schemaId,
  value,
  handleChange,
  multiple,
  disabled,
  error,
}) => {
  const [inputValue, setInputValue] = useState<string>(
    !multiple ? (value as GetEntryAttrReferral | null)?.name ?? "" : ""
  );

  const referrals = useAsync(async () => {
    return await aironeApiClientV2.getEntryAttrReferrals(schemaId, inputValue);
  }, [schemaId, inputValue]);

  const _handleChange = (
    value: GetEntryAttrReferral | GetEntryAttrReferral[] | null,
    reason: AutocompleteChangeReason
  ) => {
    if (!multiple && value != null && !Array.isArray(value)) {
      setInputValue(value.name);
    }

    if (reason === "clear") {
      if (multiple) {
        handleChange([]);
      } else {
        handleChange(null);
      }
    } else {
      handleChange(value);
    }
  };

  const handleInputChange = (
    _value: string,
    reason: AutocompleteInputChangeReason
  ) => {
    switch (reason) {
      case "input":
        setInputValue(_value);
        break;
      case "clear":
        setInputValue("");
        break;
    }
  };

  const handleBlur = () => {
    if (!multiple && value != null && !Array.isArray(value)) {
      setInputValue(value.name);
    }
  };

  return (
    <Autocomplete
      sx={{ width: "280px" }}
      multiple={multiple}
      disabled={disabled}
      loading={referrals.loading}
      options={referrals.value ?? []}
      value={value}
      inputValue={inputValue}
      getOptionLabel={(option) => option?.name ?? "-NOT SET-"}
      isOptionEqualToValue={(option, value) => option.id === value.id}
      onChange={(_e, value, reason) => _handleChange(value, reason)}
      onInputChange={(e, value, reason) => handleInputChange(value, reason)}
      onBlur={handleBlur}
      renderInput={(params) => (
        <TextField
          {...params}
          error={error != null}
          helperText={error?.message}
          size="small"
          placeholder={multiple ? "" : "-NOT SET-"}
        />
      )}
    />
  );
};
