import { z } from "zod";

import { Role } from "../../apiclient/autogenerated";
import { schemaForType } from "../../services/ZodSchemaUtil";

// FIXME with typescript strict
const Schema = schemaForType<Role>()(
  z.object({
    id: z.number(),
    name: z.string(),
    description: z.string().optional(),
    users: z.object({
      id: z.number(),
      name: z.string(),
    }),
    groups: z.object({
      id: z.number(),
      name: z.string(),
    }),
    adminUsers: z.object({
      id: z.number(),
      name: z.string(),
    }),
    adminGroups: z.object({
      id: z.number(),
      name: z.string(),
    }),
  })
);

export type Schema = z.infer<typeof Schema>;
