#!/bin/bash

set -u

# detect errors on spectacular
generr=$(./virtualenv/bin/python manage.py spectacular 2>&1 > /dev/null | grep ERROR);
if [ "$generr" != "" ]; then
  echo "Error(s) occur on generating OpenAPI spec from API implementation:";
  echo "$generr";
  exit 1;
fi

# generate OpenAPI spec
./virtualenv/bin/python manage.py spectacular --file spec.yaml;

# generate/format client code
dst=${1:-frontend/src/apiclient/autogenerated}
docker run --rm -u "$(id -u):$(id -g)" -v "${PWD}:/local" openapitools/openapi-generator-cli:v5.4.0 generate -i /local/spec.yaml -g typescript-fetch -o /local/"$dst" --additional-properties=typescriptThreePlus=true;
npx prettier --write "$dst"