#!/bin/bash

set -u

generr=$(./virtualenv/bin/python manage.py spectacular --file spec.yaml 2>&1 > /dev/null | grep ERROR);
if [ "$generr" != "" ]; then
  echo "Error(s) occur on generating OpenAPI spec from API implementation:";
  echo "$generr";
  exit 1;
fi

docker run --rm -u "$(id -u):$(id -g)" -v "${PWD}:/local" openapitools/openapi-generator-cli:v5.4.0 generate -i /local/spec.yaml -g typescript-fetch -o /local/apiclient/typescript-fetch/src/autogenerated --additional-properties=typescriptThreePlus=true;

npm run fix;
