name: Build frontend

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'frontend/**/*.ts'
      - 'frontend/**/*.tsx'
      - '.github/workflows/build-frontend.yml'
      - 'package-lock.json'
      - '*.config.{js,mjs}'

jobs:
  lint:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
          scope: '@dmm-com'
          cache: 'npm'
      - name: install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: lint
        run: npm run lint
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
          scope: '@dmm-com'
          cache: 'npm'
      - name: install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: build
        run: npm run build:development
      - name: build(library)
        run: npm run build:lib
  test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
          scope: '@dmm-com'
          cache: 'npm'
      - name: install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: test
        run: npm run test
      - name: Upload coverage report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: coverage-frontend
          path: coverage/lcov.info

  report-coverage:
    runs-on: ubuntu-24.04
    needs: test
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Download coverage report
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: coverage-frontend
          path: coverage
      - name: octocov
        uses: k1LoW/octocov-action@b3b6ee60482a667950f87553abf1df63217235d9 # v1
        with:
          config: .octocov.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
